"""add carira table

Revision ID: 6301bca1d628
Revises: 07c7ae795a24
Create Date: 2025-07-23 12:49:16.322930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "6301bca1d628"
down_revision: Union[str, None] = "07c7ae795a24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carira_features",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_uuid", sa.UUID(), nullable=False),
        sa.Column("property_code", sa.String(), nullable=True),
        sa.Column("municipality", sa.String(), nullable=True),
        sa.Column("area_id", sa.String(), nullable=True),
        sa.Column("area_name", sa.String(), nullable=True),
        sa.Column("app_area", sa.Float(), nullable=True),
        sa.Column("total_area", sa.Float(), nullable=True),
        sa.Column("biomass_area", sa.Float(), nullable=True),
        sa.Column("carbon_area", sa.Float(), nullable=True),
        sa.Column("soil_carbon", sa.Float(), nullable=True),
        sa.Column("tree_carbon", sa.Float(), nullable=True),
        sa.Column("herbaceous_carbon", sa.Float(), nullable=True),
        sa.Column("litter_carbon", sa.Float(), nullable=True),
        sa.Column("total_carbon", sa.Float(), nullable=True),
        sa.Column("annual_carbon_capture", sa.Float(), nullable=True),
        sa.Column("co2_emission", sa.Float(), nullable=True),
        sa.Column("monitoring_date", sa.Date(), nullable=True),
        sa.Column("vegetation_type", sa.String(), nullable=True),
        sa.Column("land_use", sa.String(), nullable=True),
        sa.Column("reforestation_age", sa.Integer(), nullable=True),
        sa.Column("estimation_method", sa.String(), nullable=True),
        sa.Column("data_source", sa.String(), nullable=True),
        sa.Column("estimation_error", sa.Float(), nullable=True),
        sa.Column("responsible", sa.String(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("carira_features")
    # ### end Alembic commands ###
